import React,{useState} from 'react';
import {TraceTree} from '../vendor/langfuse/web/src/features/traces/components/TraceTree';
import {ScoreBadge} from '../vendor/langfuse/web/src/components/ScoreBadge/ScoreBadge';
import {FixtureContext} from '../vendor/langfuse/web/src/fixture-context';
import {ItemTypeIcon} from '../vendor/langfuse/web/src/components/ItemBadge';
import {systemFor,byDef} from './model.mjs';
import PayloadView,{Json} from './PayloadView';
export function Record({record:s}:any){return <article className="score-record"><div className="native-scope">{s.value===null?<span className="null-score">{s.name}: not applicable</span>:<ScoreBadge name={s.name} scores={[s]}/>}</div><p>{s.comment}</p><small>{s.producer} · {s.stage} · {s.evidence}</small><code>{s.id}</code><code>Observation: {s.observationId}</code><details><summary>Rubric & identity</summary><p>{byDef(s.definitionId)?.rubric}</p><Json value={{definition:s.definitionId,revision:'r1',traceId:s.traceId,sessionId:s.sessionId,target:s.observationId,status:s.status}}/></details></article>}
export default function TraceView({trace:t,scores,selected,setSelected,onSession}:any){const [collapsed,setCollapsed]=useState(new Set<string>());const [tab,setTab]=useState('Input / output');const n=t.nodes.find((n:any)=>n.id===selected)||t.root;const attached=scores.filter((s:any)=>s.observationId===n.id),traceScores=scores.filter((s:any)=>s.traceId===t.id);
return <><div className="facts"><span>{t.nodes.length} observations</span><span>{t.stage}</span><span>Authored timings · completed operation</span></div><div className="native-trace"><aside className="tree-column"><header><strong>Trace tree</strong><button className="ui-button" onClick={()=>setCollapsed(collapsed.size?new Set():new Set([t.rootId]))}>{collapsed.size?'Expand all':'Collapse all'}</button></header><div className="tree-container native-scope"><FixtureContext.Provider value={{roots:[t.root],comments:new Map(),mergedScores:traceScores.map((record:any)=>({...record,comment:undefined})),selectedNodeId:n.id,collapsedNodes:collapsed,toggleCollapsed:(id:string)=>setCollapsed(old=>{const s=new Set(old);s.has(id)?s.delete(id):s.add(id);return s;}),selectNode:setSelected}}><TraceTree/></FixtureContext.Provider></div><footer><button className="ui-button" onClick={()=>onSession(t.sessionId)}>Open session ↗</button><code>{t.sessionId}</code></footer></aside><section className="detail-column"><header><span className="native-scope"><ItemTypeIcon type={n.type}/></span><strong>{n.name}</strong><span className="pill">{n.id===t.rootId?'ROOT':n.type}</span></header><nav className="tabs">{['Input / output','Scores','Prompt & model','Identity'].map(v=><button key={v} onClick={()=>setTab(v)} aria-pressed={tab===v}>{v}{v==='Scores'?' · '+attached.length:''}</button>)}</nav><div className="detail-content">{tab==='Input / output'&&<><PayloadView title="Input" value={n.input}/><PayloadView title="Output" value={n.output}/><details><summary>Evaluator context and metadata</summary><Json value={n.metadata}/></details></>}{tab==='Scores'&&<><h3>{attached.length} outcomes on this {n.id===t.rootId?'request root':'operation'}</h3><code>{n.id}</code>{attached.map((s:any)=><Record key={s.id} record={s}/>)}{!attached.length&&<p>No scores on this operation. An unscored operation is not a failed one.</p>}</>}{tab==='Prompt & model'&&<>{n.type==='GENERATION'?<><h3>{n.name} · v{n.promptVersion}</h3><p className="message-text">{systemFor(n.promptId,n.promptVersion)}</p><Json value={{promptId:n.promptId,version:n.promptVersion,model:n.model,usage:n.usageDetails,evidence:'Authored example; exact upstream prompt content for PR-01 v7/v9, task template elsewhere.'}}/></>:<p>This operation does not call a prompt. Select a generation to inspect its resolved version.</p>}</>}{tab==='Identity'&&<Json value={{traceId:t.id,observationId:n.id,parentObservationId:n.parentObservationId,isRootObservation:n.id===t.rootId,sessionId:n.sessionId}}/>}</div></section></div><p className="caption">Actual Langfuse trace tree, type rows and score badges · revision 9aca47c. The detail inspector is local; services use fixtures.</p></>}
